language: php
php:
  - '7.1'
  - '7.2'

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libreoffice

script:
  - phpunit
